test : test.cpp
	clang++ test.cpp --std=c++11 -o test

lagrange : lagrange.cpp
	clang++ lagrange.cpp --std=c++11 -o lagrange

newton : newton.cpp
	clang++ newton.cpp --std=c++11 -o newton

clean :
	rm newton lagrange test
	echo Clean done
